### ISSUE TITLE
Corrupt File?

### ISSUE THREAD

**Issue by funnybananas** [Wh04m1001/IDiagnosticProfileUAC#3]
Maybe I'm not understanding the code well enough, but any idea why the resulting DLL in System32 is only 36 bytes once moved?

**Comment by Wh04m1001** [comment]
idk but here  i just tested ,everything works fine 
![image](https://user-images.githubusercontent.com/44291883/177387487-62c36778-3ea2-433a-badf-f207da0e65bc.png)

**Comment by funnybananas** [comment]
Looks like it creates the empty cab file, but with the .dll extension and that's what gets put into System32
